CREATE TABLE public.call_center (
	cc_call_center_sk int8 NOT NULL,
	cc_call_center_id char(16) NOT NULL,
	cc_rec_start_date date,
	cc_rec_end_date date,
	cc_closed_date_sk int8,
	cc_open_date_sk int8,
	cc_name varchar(50),
	cc_class varchar(50),
	cc_employees int8,
	cc_sq_ft int8,
	cc_hours varchar(20),
	cc_manager varchar(40),
	cc_mkt_id int8,
	cc_mkt_class varchar(50),
	cc_mkt_desc varchar(100),
	cc_market_manager varchar(40),
	cc_division int8,
	cc_division_name varchar(50),
	cc_company int8,
	cc_company_name varchar(50),
	cc_street_number varchar(10),
	cc_street_name varchar(60),
	cc_street_type varchar(15),
	cc_suite_number varchar(10),
	cc_city varchar(60),
	cc_county varchar(30),
	cc_state char(2),
	cc_zip char(10),
	cc_country varchar(20),
	cc_gmt_offset numeric(5,2),
	cc_tax_percentage numeric(5,2)
);

CREATE TABLE public.catalog_sales (
	cs_sold_date_sk int8,
	cs_sold_time_sk int8,
	cs_ship_date_sk int8,
	cs_bill_customer_sk int8,
	cs_bill_cdemo_sk int8,
	cs_bill_hdemo_sk int8,
	cs_bill_addr_sk int8,
	cs_ship_customer_sk int8,
	cs_ship_cdemo_sk int8,
	cs_ship_hdemo_sk int8,
	cs_ship_addr_sk int8,
	cs_call_center_sk int8,
	cs_catalog_page_sk int8,
	cs_ship_mode_sk int8,
	cs_warehouse_sk int8,
	cs_item_sk int8 NOT NULL,
	cs_promo_sk int8,
	cs_order_number int8 NOT NULL,
	cs_quantity int8,
	cs_wholesale_cost numeric(7,2),
	cs_list_price numeric(7,2),
	cs_sales_price numeric(7,2),
	cs_ext_discount_amt numeric(7,2),
	cs_ext_sales_price numeric(7,2),
	cs_ext_wholesale_cost numeric(7,2),
	cs_ext_list_price numeric(7,2),
	cs_ext_tax numeric(7,2),
	cs_coupon_amt numeric(7,2),
	cs_ext_ship_cost numeric(7,2),
	cs_net_paid numeric(7,2),
	cs_net_paid_inc_tax numeric(7,2),
	cs_net_paid_inc_ship numeric(7,2),
	cs_net_paid_inc_ship_tax numeric(7,2),
	cs_net_profit numeric(7,2)
);

CREATE TABLE public.customer (
	c_customer_sk int8 NOT NULL,
	c_customer_id char(16) NOT NULL,
	c_current_cdemo_sk int8,
	c_current_hdemo_sk int8,
	c_current_addr_sk int8,
	c_first_shipto_date_sk int8,
	c_first_sales_date_sk int8,
	c_salutation char(10),
	c_first_name char(20),
	c_last_name char(30),
	c_preferred_cust_flag char(1),
	c_birth_day int8,
	c_birth_month int8,
	c_birth_year int8,
	c_birth_country varchar(20),
	c_login char(13),
	c_email_address char(50),
	c_last_review_date int8
);

CREATE TABLE public.date_dim (
	d_date_sk int8 NOT NULL,
	d_date_id char(16) NOT NULL,
	d_date date,
	d_month_seq int8,
	d_week_seq int8,
	d_quarter_seg int8,
	d_year int8,
	d_dow int8,
	d_moy int8,
	d_dom int8,
	d_qoy int8,
	d_fy_year int8,
	d_fy_quarter_seq int8,
	d_fy_week_seq int8,
	d_day_name char(9),
	d_quarter_name char(6),
	d_holiday char(1),
	d_weekend char(1),
	d_following_holiday char(1),
	d_first_dom int8,
	d_last_dom int8,
	d_same_day_1y int8,
	d_same_day_1q int8,
	d_current_day char(1),
	d_current_week char(1),
	d_current_month char(1),
	d_current_quarter char(1),
	d_current_year char(1)
);

CREATE TABLE public.household_demographics (
	hd_demo_sk int8 NOT NULL,
	hd_income_band_sk int8 NOT NULL,
	hd_buy_potential char(15),
	hd_dep_count int8,
	hd_vehicle_count int8
);

CREATE TABLE public.item (
	i_item_sk int8 NOT NULL,
	i_item_id char(16) NOT NULL,
	i_rec_start_date date,
	i_rec_end_date date,
	i_item_desc varchar(200),
	i_current_price numeric(7,2),
	i_wholesale_cost numeric(7,2),
	i_brand_id int8,
	i_brand char(50),
	i_class_id int8,
	i_class char(50),
	i_category_id int8,
	i_category char(50),
	i_manufact_id int8,
	i_manufact char(50),
	i_size char(20),
	i_formulation char(20),
	i_color char(20),
	i_units char(10),
	i_container char(10),
	i_manager_id int8,
	i_product_name char(50)
);

CREATE TABLE public.store (
	s_store_sk int8 NOT NULL,
	s_store_id char(16) NOT NULL,
	s_rec_start_date date,
	s_rec_end_date date,
	s_closed_date_sk int8,
	s_store_name varchar(50),
	s_number_employees int8,
	s_floor_space int8,
	s_hours char(20),
	s_manager varchar(40),
	s_market_id int8,
	s_geography_class varchar(100),
	s_market_desc varchar(100),
	s_market_manager varchar(40),
	s_division_id int8,
	s_division_name varchar(40),
	s_company_id int8,
	s_company_name varchar(50),
	s_street_number varchar(10),
	s_street_name varchar(60),
	s_street_type varchar(15),
	s_suite_number varchar(10),
	s_city varchar(60),
	s_county varchar(30),
	s_state char(2),
	s_zip char(10),
	s_country varchar(20),
	s_gmt_offset numeric(5,2),
	s_tax_percentage numeric(5,2)
);

CREATE TABLE public.store_sales (
	ss_sold_date_sk int8,
	ss_sold_time_sk int8,
	ss_item_sk int8 NOT NULL,
	ss_customer_sk int8,
	ss_cdemo_sk int8,
	ss_hdemo_sk int8,
	ss_addr_sk int8,
	ss_store_sk int8,
	ss_promo_sk int8,
	ss_ticket_number int8 NOT NULL,
	ss_quantity int8,
	ss_wholesale_cost numeric(7,2),
	ss_list_price numeric(7,2),
	ss_sales_price numeric(7,2),
	ss_ext_discount_amt numeric(7,2),
	ss_ext_sales_price numeric(7,2),
	ss_ext_wholesale_cost numeric(7,2),
	ss_ext_list_price numeric(7,2),
	ss_ext_tax numeric(7,2),
	ss_coupon_amt numeric(7,2),
	ss_net_paid numeric(7,2),
	ss_net_paid_inc_tax numeric(7,2),
	ss_net_profit numeric(7,2)
);

CREATE TABLE public.web_sales (
	ws_sold_date_sk int8,
	ws_sold_time_sk int8,
	ws_ship_date_sk int8,
	ws_item_sk int8 NOT NULL,
	ws_bill_customer_sk int8,
	ws_bill_cdemo_sk int8,
	ws_bill_hdemo_sk int8,
	ws_bill_addr_sk int8,
	ws_ship_customer_sk int8,
	ws_ship_cdemo_sk int8,
	ws_ship_hdemo_sk int8,
	ws_ship_addr_sk int8,
	ws_web_page_sk int8,
	ws_web_site_sk int8,
	ws_ship_mode_sk int8,
	ws_warehouse_sk int8,
	ws_promo_sk int8,
	ws_order_number int8 NOT NULL,
	ws_quantity int8,
	ws_wholesale_cost numeric(7,2),
	ws_list_price numeric(7,2),
	ws_sales_price numeric(7,2),
	ws_ext_discount_amt numeric(7,2),
	ws_ext_sales_price numeric(7,2),
	ws_ext_wholesale_cost numeric(7,2),
	ws_ext_list_price numeric(7,2),
	ws_ext_tax numeric(7,2),
	ws_coupon_amt numeric(7,2),
	ws_ext_ship_cost numeric(7,2),
	ws_net_paid numeric(7,2),
	ws_net_paid_inc_tax numeric(7,2),
	ws_net_paid_inc_ship numeric(7,2),
	ws_net_paid_inc_ship_tax numeric(7,2),
	ws_net_profit numeric(7,2)
);
